import { Button } from 'antd'
import axios from 'axios'
import Head from 'next/head'
export default function Home(props) {
  const asd = props.users.map((e, i) => {
    return (
      <div key={i}>
        <p key={i}>{e.email}</p>
        <Button key={i} type='primary'>click</Button>
      </div>
    )
  })
  return (
    <div>
      <Head>
        <title>New Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello Next + AntD
        {asd}
      </div>
    </div>
  )
}

// export const 
Home.getInitialProps = async (ctx) => {
  const url = process.env.URL
  const res = await (await axios.get(`${url}/api/users`)).data
  return { users: res }
}