import axios from 'axios'
import Head from 'next/head'
export default function Home(props) {
  console.log('file: index.js ~ line 4 ~ props', props)
  return (
    <div>
      <Head>
        <title>New Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello Next + AntD
      </div>
    </div>
  )
}

// export const 
Home.getInitialProps = async (ctx) => {
  const res = await (await axios.get('http://localhost:3000/api/users')).data
  console.log('file: index.js ~ line 22 ~ res', res)
  return { res }
}